# _config.yml

# General settings
title: "Antonio Olivas-Martínez"
author: "Antonio Olivas-Martínez"
description: "Personal academic website"
url: "https://yourusername.github.io" # Update with your GitHub Pages URL
baseurl: "" # Leave empty for root URL, or use a subpath (e.g., /personal-site)

# Social Media Links
social_links:
  - { icon: "fab fa-linkedin", url: "https://www.linkedin.com/in/antonio-olivas-martinez-490236198/" }
  - { icon: "fab fa-researchgate", url: "https://www.researchgate.net/profile/Antonio-Olivas-Martinez" }

# Navigation Links
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Research"
    url: "/research/"
  - title: "Blog"
    url: "/blog/"
  - title: "Contact"
    url: "/contact/"

# Enable blog posts and page-specific configurations
blog:
  enabled: true

# Markdown and liquid settings
markdown: kramdown
highlighter: rouge

# Theme (Minimal Mistakes)
theme: "minimal-mistakes-jekyll"
